### ISSUE TITLE
Can't reorientate logos for titles using assets generated from Steam ROM Manager (potentially more)

### ISSUE THREAD

**Issue by CarJem** [SteamGridDB/decky-steamgriddb#39]
**Steps to reproduce:**
1. Add game via Steam ROM Manager with Logo
2. Use Plugin to move the Logo
3. The loading symbol appears until pressing the d-pad, then, it's taking up the whole space and is not orientable.

**Images Used + Shortcuts.vdf**
- Using the Game titled "Bionicle Heroes"
[TestData.zip](https://github.com/SteamGridDB/decky-steamgriddb/files/10808599/TestData.zip)

**Comment by doZennn** [comment]
Can't reproduce but possibly fixed in https://github.com/SteamGridDB/decky-steamgriddb/commit/c461243f985f27ecaf99a843902c58bccc4abc24

**Comment by CarJem** [comment]
It now actually functions, however still does not update It's position unless you update it manually.

**Comment by doZennn** [comment]
Can you elaborate?

**Comment by CarJem** [comment]
basically... The initial state of the logo will be blown up to maximum size until you adjust its size

**Comment by doZennn** [comment]
Still can't reproduce this, and had no other reports. Closing but feel free to reopen if you can give me reproducible steps.
